name: christmas_bingo
description: "Mami Bingo Bongo"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  firebase_auth: ^5.3.0
  provider: ^6.1.2
  confetti: ^0.8.0
  flutter_fireworks: ^1.0.7



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  fonts:
    - family: NotoEmoji
      fonts:
        - asset: assets/Noto_Emoji/static/NotoEmoji-Regular.ttf
        - asset: assets/Noto_Emoji/static/NotoEmoji-Bold.ttf
        - asset: assets/Noto_Emoji/static/NotoEmoji-Light.ttf
        - asset: assets/Noto_Emoji/static/NotoEmoji-Medium.ttf
        - asset: assets/Noto_Emoji/static/NotoEmoji-SemiBold.ttf
        - asset: assets/Noto_Emoji/NotoEmoji-VariableFont_wght.ttf
