// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXms34_6UbIpgxmNZmpe9OuaAMvWHWPO4',
    appId: '1:746387219372:web:a9def5b99f0521ada35009',
    messagingSenderId: '746387219372',
    projectId: 'christmas-bingo-89281',
    authDomain: 'christmas-bingo-89281.firebaseapp.com',
    storageBucket: 'christmas-bingo-89281.firebasestorage.app',
    measurementId: 'G-13F3FKYKKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxxKL37AsADqU4HG0301qynCaEGlMHp8',
    appId: '1:746387219372:android:baf22ca712b352bfa35009',
    messagingSenderId: '746387219372',
    projectId: 'christmas-bingo-89281',
    storageBucket: 'christmas-bingo-89281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCmx3YZX28FXFDnNZsH3UJN92GyMINgI',
    appId: '1:746387219372:ios:e8df4d5d0bcda71ea35009',
    messagingSenderId: '746387219372',
    projectId: 'christmas-bingo-89281',
    storageBucket: 'christmas-bingo-89281.firebasestorage.app',
    iosBundleId: 'com.example.christmasBingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCmx3YZX28FXFDnNZsH3UJN92GyMINgI',
    appId: '1:746387219372:ios:e8df4d5d0bcda71ea35009',
    messagingSenderId: '746387219372',
    projectId: 'christmas-bingo-89281',
    storageBucket: 'christmas-bingo-89281.firebasestorage.app',
    iosBundleId: 'com.example.christmasBingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXms34_6UbIpgxmNZmpe9OuaAMvWHWPO4',
    appId: '1:746387219372:web:401ddff0554d6a66a35009',
    messagingSenderId: '746387219372',
    projectId: 'christmas-bingo-89281',
    authDomain: 'christmas-bingo-89281.firebaseapp.com',
    storageBucket: 'christmas-bingo-89281.firebasestorage.app',
    measurementId: 'G-1DPCM74GX8',
  );
}
